<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FantasyTeamController;
use App\Http\Controllers\LeagueController;
use App\Http\Controllers\PlayerController;
use App\Http\Controllers\FixtureController;
use App\Http\Controllers\TransferController;
use App\Http\Controllers\StatisticController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\GoogleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Welcome Page Route
Route::get('/', function () {
    return view('welcome');
})->name('home');

// Authentication Routes (generated by Breeze)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    // Profile Routes (from Breeze)
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    
    // Dashboard Routes
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    
    // Fantasy Team Management Routes
    Route::resource('fantasy-team', FantasyTeamController::class);

    // Player Selection Routes (NEW - Add these)
    Route::prefix('players')->group(function () {
        Route::get('/', [PlayerController::class, 'index'])->name('players.index');
        Route::get('/select/{position}', [PlayerController::class, 'select'])->name('players.select');
        Route::post('/add-to-team', [PlayerController::class, 'addToTeam'])->name('players.add-to-team');
        Route::get('/search', [PlayerController::class, 'search'])->name('players.search');
        Route::get('/{player}', [PlayerController::class, 'show'])->name('players.show');
        Route::get('/position/{position}', [PlayerController::class, 'byPosition'])->name('players.by-position');
    });
    
    
    // League Routes
   Route::prefix('leagues')->group(function () {
    Route::get('/', [LeagueController::class, 'index'])->name('leagues.index');
    Route::get('/create', [LeagueController::class, 'create'])->name('leagues.create');
    Route::post('/', [LeagueController::class, 'store'])->name('leagues.store');
    Route::get('/{league}', [LeagueController::class, 'show'])->name('leagues.show');
    Route::get('/{league}/join', [LeagueController::class, 'join'])->name('leagues.join');
    Route::get('/{league}/leave', [LeagueController::class, 'leave'])->name('leagues.leave');
});
    
    // Player Routes
    Route::prefix('players')->group(function () {
        Route::get('/', [PlayerController::class, 'index'])->name('players.index');
        Route::get('/search', [PlayerController::class, 'search'])->name('players.search');
        Route::get('/{player}', [PlayerController::class, 'show'])->name('players.show');
        Route::get('/position/{position}', [PlayerController::class, 'byPosition'])->name('players.by-position');
    });
    
    // Fixture Routes
    Route::prefix('fixtures')->group(function () {
        Route::get('/', [FixtureController::class, 'index'])->name('fixtures.index');
        Route::get('/upcoming', [FixtureController::class, 'upcoming'])->name('fixtures.upcoming');
        Route::get('/{fixture}', [FixtureController::class, 'show'])->name('fixtures.show');
    });
    
    // Transfer Routes
    Route::prefix('transfers')->group(function () {
        Route::get('/transfers', [TransferController::class, 'index'])->name('transfers.index');
        Route::get('/make', [TransferController::class, 'create'])->name('transfers.create');
        Route::post('/', [TransferController::class, 'store'])->name('transfers.store');
        Route::get('/history', [TransferController::class, 'history'])->name('transfers.history');
        Route::get('/wildcard', [TransferController::class, 'wildcard'])->name('transfers.wildcard');
        Route::post('/wildcard', [TransferController::class, 'useWildcard'])->name('transfers.use-wildcard');
    });
    
    // Statistics Routes
    Route::prefix('statistics')->group(function () {
        Route::get('/', [StatisticController::class, 'index'])->name('statistics.index');
        Route::get('/players', [StatisticController::class, 'players'])->name('statistics.players');
        Route::get('/teams', [StatisticController::class, 'teams'])->name('statistics.teams');
        Route::get('/points', [StatisticController::class, 'points'])->name('statistics.points');
    });
    
    // Additional Dashboard Functionality
    Route::get('/notifications', [DashboardController::class, 'notifications'])->name('notifications');
    Route::post('/notifications/mark-read', [DashboardController::class, 'markNotificationsAsRead'])->name('notifications.mark-read');
    Route::get('/points', [DashboardController::class, 'points'])->name('points');
    Route::get('/rank', [DashboardController::class, 'rank'])->name('rank');
});

// Authentication Routes (generated by Breeze)
require __DIR__.'/auth.php';