<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FantasyTeamController;
use App\Http\Controllers\LeagueController;
use App\Http\Controllers\PlayersController;
use App\Http\Controllers\FixturesController;
use App\Http\Controllers\TransferController;
use App\Http\Controllers\StatisticsController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\GoogleController;
use Laravel\Socialite\Facades\Socialite;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Welcome Page Route
Route::get('/', function () {
    return view('welcome');
})->name('home');
Route::view('/features', 'features')->name('features');
Route::view('/how-it-works', 'how-it-works')->name('how-it-works');


// Authentication Routes (generated by Breeze)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/register', function () {
    // Fetch team data
    $response = Http::get('https://fantasy.premierleague.com/api/bootstrap-static/');
    $teams = collect($response->json()['teams'])->map(function ($team) {
        return (object) [
            'id' => $team['id'],
            'name' => $team['name'],
            'short_name' => $team['short_name'],
            'code' => $team['code'],
        ];
    });

    return view('auth.register', compact('teams'));
})->name('register');

Route::get('auth/google', function () {
    return Socialite::driver('google')->redirect();
})->name('google.login');

Route::get('auth/google/callback', function () {
    $googleUser = Socialite::driver('google')->stateless()->user();

    $user = User::firstOrCreate(
        ['email' => $googleUser->getEmail()],
        [
            'name' => $googleUser->getName(),
            'password' => bcrypt(str()->random(16)), // random password
        ]
    );

    Auth::login($user);

    return redirect()->route('dashboard');
});

Route::middleware('auth')->group(function () {
    // Profile Routes (from Breeze)
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    
    // Dashboard Routes
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    
    // Fantasy Team Management Routes
   Route::middleware(['auth'])->group(function() {
    Route::get('/fantasy-team/create', [FantasyTeamController::class, 'create'])
    ->name('fantasy-team.create');
    Route::get('/fantasy-team', [FantasyTeamController::class, 'index'])->name('fantasy-team.index');
    Route::post('/fantasy-team/store', [FantasyTeamController::class, 'store'])->name('fantasy-team.store');
});

    // Player Selection Routes (NEW - Add these)
    Route::prefix('players')->group(function () {
        Route::get('/', [PlayerController::class, 'index'])->name('players.index');
        Route::get('/select/{position}', [PlayerController::class, 'select'])->name('players.select');
        Route::post('/add-to-team', [PlayerController::class, 'addToTeam'])->name('players.add-to-team');
        Route::get('/search', [PlayerController::class, 'search'])->name('players.search');
        Route::get('/{player}', [PlayerController::class, 'show'])->name('players.show');
        Route::get('/position/{position}', [PlayerController::class, 'byPosition'])->name('players.by-position');
    });
    
    
    // League Routes
   Route::prefix('leagues')->group(function () {
    Route::get('/', [LeagueController::class, 'index'])->name('leagues.index');
    Route::get('/create', [LeagueController::class, 'create'])->name('leagues.create');
    Route::post('/', [LeagueController::class, 'store'])->name('leagues.store');
    Route::resource('leagues', LeagueController::class);
    Route::post('/leagues/{league}/join', [LeagueController::class, 'join'])->name('leagues.join');
    Route::post('/leagues/{id}/leave', [LeagueController::class, 'leave'])->name('leagues.leave');
});
    
    // Player Routes
    Route::get('/players', [PlayersController::class, 'index'])->name('players.index');
    Route::get('/players/search', [PlayersController::class, 'search'])->name('players.search');
    
    // Fixture Routes
    Route::get('/fixtures', [App\Http\Controllers\FixturesController::class, 'index'])
     ->name('fixtures.index');
    
    // Transfer Routes
    Route::prefix('transfers')->group(function () {
        Route::get('/transfers', [TransferController::class, 'index'])->name('transfers.index');
        Route::post('/transfers/confirm', [TransferController::class, 'confirm'])->name('transfers.confirm');
    });

    // Statistics routes
    Route::prefix('statistics')->group(function () {
        Route::get('/', [StatisticsController::class, 'index'])->name('statistics.index');
        Route::get('/players', [StatisticsController::class, 'players'])->name('statistics.players');
        Route::get('/teams', [StatisticsController::class, 'teams'])->name('statistics.teams');
    });

    
    // Additional Dashboard Functionality
    Route::get('/notifications', [DashboardController::class, 'notifications'])->name('notifications');
    Route::post('/notifications/mark-read', [DashboardController::class, 'markNotificationsAsRead'])->name('notifications.mark-read');
    Route::get('/points', [DashboardController::class, 'points'])->name('points');
    Route::get('/rank', [DashboardController::class, 'rank'])->name('rank');
    Route::view('/help', 'help')->name('help');
});

// Authentication Routes (generated by Breeze)
require __DIR__.'/auth.php';